"""Fail-closed compiler gates for the v4 reporting IR.

The compiler validates a DocumentIR before any renderer may consume it. v4
adds finding / clause / render-contract gates on top of the v3 ID / citation /
dedup / structure gates. Existing v3-style documents (no findings, no clauses)
still compile through the legacy gates unchanged; BCR documents exercise the
new gates strictly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from backend.common.reporting.schema import DocumentIR
from backend.common.reporting.schema.citations import CitationRegistry
from backend.common.reporting.schema.diagnostics import Diagnostic, DiagnosticLocation

_RESIDUAL_MARKER_RE = re.compile(r"\{\{(?:CIT-[^}]+|[^}]+)\}\}")
_BOLD_RE = re.compile(r"\*\*|(?<!\w)__")
_FOOTNOTE_RE = re.compile(r"(?<!\w)\[(\d+)\]")

# task068 T10 — raw request JSON / absolute filesystem paths must never reach
# report body text. These are *narrow* fingerprints (a JSON object with a quoted
# key, a JSON array of objects, an absolute POSIX/Windows path, a ``file:///``
# URI, and well-known debug field names), not a blanket brace/path ban.
_RAW_JSON_OBJECT_RE = re.compile(r"\{[^{}\n]*\"[^\"]+\"\s*:")
_RAW_JSON_ARRAY_RE = re.compile(r"\[\s*\{" )
_ABS_PATH_RE = re.compile(
    r"(?ix)(?:^|[\s\"'<(])"
    r"(?:(?:/[A-Za-z0-9_.-]+)+/?|"        # POSIX absolute path (one or more segments)
    r"[A-Za-z]:\\[\\A-Za-z0-9_.-]+|"      # Windows drive path (single backslash)
    r"file:///)"
)
_DEBUG_FIELD_RE = re.compile(
    r"\b(?:storage_uri|business_model|model_dump|checksum_sha256|"
    r"attachment_metadata|trace_manifest_path)\b"
)

MAX_CLAUSE_DEPTH = 4
KNOWN_PROFILE_IDS = {"legal-report-a4-v1"}

# task068 I068-22 — ``FindingBasis.rationale`` must be an *attribution* from an
# existing business field, never generated by the renderer or a fresh LLM call.
# These fingerprints catch LLM refusal/placeholder text that would betray a
# fabricated rationale. (Chinese + English + generic placeholder forms.)
_ILLEGAL_RATIONALE_FINGERPRINTS = (
    re.compile(r"作为\s*(?:人工智能|AI|语言模型)"),
    re.compile(r"(?i)as an (?:AI|artificial intelligence|language model)"),
    re.compile(r"(?i)i (?:cannot|can't|do not have|don't have|am unable)"),
    re.compile(r"无法(?:提供|确定|判断|给出|回答)"),
    re.compile(r"(?i)\b(TODO|TBD|FIXME|PLACEHOLDER|PENDING|XXX)\b"),
    re.compile(r"待(?:补充|填写|完善|确认)"),
    re.compile(r"\{\{|\}\}"),
)


@dataclass
class CompilerState:
    document: DocumentIR
    registry: CitationRegistry
    rendered_text: str = ""
    diagnostics: list[Diagnostic] = field(default_factory=list)


@dataclass(frozen=True)
class PassResult:
    status: str = "success"
    diagnostics: tuple[Diagnostic, ...] = ()


@dataclass(frozen=True)
class CompileResult:
    status: str
    document: DocumentIR | None
    diagnostics: tuple[Diagnostic, ...]


class CompilerPass:
    def run(self, state: CompilerState) -> PassResult:
        raise NotImplementedError


def _result(diagnostics: list[Diagnostic]) -> PassResult:
    if any(item.severity == "fatal" for item in diagnostics):
        status = "fatal"
    elif any(item.severity == "error" for item in diagnostics):
        status = "error"
    elif any(item.severity == "warning" for item in diagnostics):
        status = "warning"
    else:
        status = "success"
    return PassResult(status=status, diagnostics=tuple(diagnostics))


def _iter_blocks(document: DocumentIR):
    for section in document.sections:
        for block in section.blocks:
            yield section, block


def _iter_citation_refs(document: DocumentIR):
    """Yield citation IDs in display order (sections → blocks → clauses), then
    finding citation_refs."""
    for _section, block in _iter_blocks(document):
        for citation_id in getattr(block, "citation_refs", []):
            yield citation_id
        clauses = getattr(block, "clauses", [])
        for clause in _iter_clause_nodes(clauses):
            for citation_id in clause.citation_refs:
                yield citation_id
    for finding in document.findings:
        for citation_id in finding.citation_refs:
            yield citation_id


def _iter_clause_nodes(clauses: list):
    for clause in clauses:
        yield clause
        yield from _iter_clause_nodes(clause.children)


def _collect_finding_refs(document: DocumentIR) -> dict[str, list[str]]:
    """Map finding_id → list of block_ids of its *primary* display blocks.

    Only ``FINDING_DETAIL`` counts as the primary display. ``FINDING_REFERENCE``
    is a secondary cross-reference (e.g. an appendix pointer) and must not
    inflate ``primary_display_count``.
    """
    detail: dict[str, list[str]] = {}
    for _section, block in _iter_blocks(document):
        if getattr(block, "type", None) != "finding_detail":
            continue
        ref = getattr(block, "finding_ref", None)
        if ref is not None:
            detail.setdefault(ref, []).append(block.block_id)
    return detail


# ── v3 passes (preserved) ──────────────────────────────────────────────────


class InputValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        seen_sections: set[str] = set()
        seen_blocks: set[str] = set()
        for section in state.document.sections:
            if section.section_id in seen_sections:
                diagnostics.append(Diagnostic(
                    code="SECTION_ID_DUPLICATE",
                    severity="fatal",
                    message=f"重复的 section_id: {section.section_id}",
                    location=DiagnosticLocation(section_id=section.section_id),
                ))
            seen_sections.add(section.section_id)
            for block in section.blocks:
                if block.block_id in seen_blocks:
                    diagnostics.append(Diagnostic(
                        code="BLOCK_ID_DUPLICATE",
                        severity="error",
                        message=f"重复的 block_id: {block.block_id}",
                        location=DiagnosticLocation(section_id=section.section_id, block_id=block.block_id),
                    ))
                seen_blocks.add(block.block_id)
        return _result(diagnostics)


class CitationValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        for section in state.document.sections:
            for block in section.blocks:
                for citation_id in getattr(block, "citation_refs", []):
                    if state.registry.resolve(citation_id) is None:
                        diagnostics.append(Diagnostic(
                            code="CITATION_NOT_REGISTERED",
                            severity="error",
                            message=f"引用 ID 未注册: {citation_id}",
                            location=DiagnosticLocation(
                                section_id=section.section_id,
                                block_id=block.block_id,
                                citation_id=citation_id,
                            ),
                            suggestion="将 citation_id 注册到本次 DocumentIR 的 CitationRegistry",
                        ))
                clauses = getattr(block, "clauses", [])
                for clause in _iter_clause_nodes(clauses):
                    for citation_id in clause.citation_refs:
                        if state.registry.resolve(citation_id) is None:
                            diagnostics.append(Diagnostic(
                                code="CITATION_NOT_REGISTERED",
                                severity="error",
                                message=f"引用 ID 未注册: {citation_id}",
                                location=DiagnosticLocation(
                                    section_id=section.section_id,
                                    block_id=block.block_id,
                                    citation_id=citation_id,
                                ),
                            ))
        for finding in state.document.findings:
            for citation_id in finding.citation_refs:
                if state.registry.resolve(citation_id) is None:
                    diagnostics.append(Diagnostic(
                        code="CITATION_NOT_REGISTERED",
                        severity="error",
                        message=f"finding 引用 ID 未注册: {citation_id}",
                        location=DiagnosticLocation(citation_id=citation_id),
                    ))
        return _result(diagnostics)


class CitationNumberingPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        for citation_id in _iter_citation_refs(state.document):
            state.registry.assign_footnote_number(citation_id)
        return PassResult()


class DedupValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        seen: dict[str, tuple[str, str]] = {}
        for section in state.document.sections:
            if section.reuse_policy != "single_use":
                continue
            for block in section.blocks:
                text = getattr(block, "text", "")
                normalized = "".join(text.split()).casefold()
                if not normalized:
                    continue
                previous = seen.get(normalized)
                if previous:
                    diagnostics.append(Diagnostic(
                        code="BLOCK_DUPLICATE_SINGLE_USE",
                        severity="error",
                        message=f"single_use 内容重复: {previous[0]} 与 {section.section_id}",
                        location=DiagnosticLocation(section_id=section.section_id, block_id=block.block_id),
                    ))
                else:
                    seen[normalized] = (section.section_id, block.block_id)
        return _result(diagnostics)


class StructureValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        previous_level = 0
        seen_ordinals: dict[str, str] = {}
        for section in state.document.sections:
            if previous_level and section.level > previous_level + 1:
                diagnostics.append(Diagnostic(
                    code="SECTION_LEVEL_SKIP",
                    severity="error",
                    message=f"章节层级跳跃: H{previous_level} -> H{section.level}",
                    location=DiagnosticLocation(section_id=section.section_id),
                ))
            previous_level = section.level
            # task068 T10 — two sections must never share a display ordinal
            # (a duplicated ordinal would make cross-format section_ids order
            # ambiguous and let one section silently shadow another).
            ordinal = (section.ordinal or "").strip()
            if ordinal:
                if ordinal in seen_ordinals:
                    diagnostics.append(Diagnostic(
                        code="SECTION_ORDINAL_DUPLICATE",
                        severity="error",
                        message=(
                            f"重复的章节 ordinal {ordinal!r}: "
                            f"{seen_ordinals[ordinal]} 与 {section.section_id}"
                        ),
                        location=DiagnosticLocation(section_id=section.section_id),
                    ))
                else:
                    seen_ordinals[ordinal] = section.section_id
        return _result(diagnostics)


class RenderValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        if not state.rendered_text:
            return PassResult()
        diagnostics: list[Diagnostic] = []
        for pattern, code, message in (
            (_RESIDUAL_MARKER_RE, "RENDER_MARKER_RESIDUE", "渲染产物包含未替换模板/引用标记"),
            (_BOLD_RE, "RENDER_MARKDOWN_SYNTAX", "语义渲染产物包含未允许的粗体 Markdown 标记"),
        ):
            match = pattern.search(state.rendered_text)
            if match:
                diagnostics.append(Diagnostic(
                    code=code,
                    severity="fatal" if code == "RENDER_MARKER_RESIDUE" else "error",
                    message=message,
                ))
        return _result(diagnostics)


# ── v4 passes ──────────────────────────────────────────────────────────────


class FindingValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        findings = state.document.findings
        detail_refs = _collect_finding_refs(state.document)

        seen_findings: set[str] = set()
        for finding in findings:
            if finding.finding_id in seen_findings:
                diagnostics.append(Diagnostic(
                    code="FINDING_ID_DUPLICATE",
                    severity="error",
                    message=f"重复的 finding_id: {finding.finding_id}",
                    location=DiagnosticLocation(field="findings"),
                ))
            seen_findings.add(finding.finding_id)

        # Every referenced finding must exist; every finding must have exactly
        # one primary FINDING_DETAIL display. This is a no-op for empty
        # findings (the v3 legacy modules).
        for _section, block in _iter_blocks(state.document):
            ref = getattr(block, "finding_ref", None)
            if ref is not None and ref not in {f.finding_id for f in findings}:
                diagnostics.append(Diagnostic(
                    code="FINDING_REF_NOT_REGISTERED",
                    severity="error",
                    message=f"block 引用未注册的 finding: {ref}",
                    location=DiagnosticLocation(block_id=block.block_id),
                ))
            for ref in getattr(block, "finding_refs", []):
                if ref not in {f.finding_id for f in findings}:
                    diagnostics.append(Diagnostic(
                        code="FINDING_REF_NOT_REGISTERED",
                        severity="error",
                        message=f"block 引用未注册的 finding: {ref}",
                        location=DiagnosticLocation(block_id=block.block_id),
                    ))

        for finding in findings:
            primary_count = len(detail_refs.get(finding.finding_id, []))
            finding.primary_display_count = primary_count
            if primary_count != 1:
                diagnostics.append(Diagnostic(
                    code="FINDING_PRIMARY_DISPLAY_COUNT",
                    severity="error",
                    message=f"finding {finding.finding_id} 主展示次数为 {primary_count}，必须为 1",
                    location=DiagnosticLocation(field="findings"),
                ))
        return _result(diagnostics)


class BasisValidationPass(CompilerPass):
    """task068 I068-22 — validate per-citation ``FindingBasis`` entries.

    Every ``citation_ref`` must resolve to a registered citation (label-only
    entries are allowed and carry no ``citation_ref``), and ``rationale`` must
    not contain LLM refusal/placeholder text (it must be an attribution from an
    existing business field, never freshly generated).
    """

    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        for finding in state.document.findings:
            for index, basis in enumerate(finding.basis_entries):
                if basis.citation_ref is not None and state.registry.resolve(basis.citation_ref) is None:
                    diagnostics.append(Diagnostic(
                        code="BASIS_CITATION_NOT_REGISTERED",
                        severity="error",
                        message=(
                            f"finding {finding.finding_id} basis_entries[{index}] 引用未注册的 "
                            f"citation: {basis.citation_ref}"
                        ),
                        location=DiagnosticLocation(field="basis_entries", citation_id=basis.citation_ref),
                    ))
                for pattern in _ILLEGAL_RATIONALE_FINGERPRINTS:
                    if pattern.search(basis.rationale):
                        diagnostics.append(Diagnostic(
                            code="BASIS_RATIONALE_ILLEGAL_GENERATED",
                            severity="error",
                            message=(
                                f"finding {finding.finding_id} basis_entries[{index}] rationale 含 "
                                f"LLM/占位符签名，必须归因自既有业务字段"
                            ),
                            location=DiagnosticLocation(field="basis_entries"),
                        ))
                        break
        return _result(diagnostics)


class ClauseStructureValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        seen_nodes: set[str] = set()

        def _walk(clauses, depth: int) -> None:
            for clause in clauses:
                if clause.node_id in seen_nodes:
                    diagnostics.append(Diagnostic(
                        code="CLAUSE_NODE_ID_DUPLICATE",
                        severity="error",
                        message=f"重复的 clause node_id: {clause.node_id}",
                        location=DiagnosticLocation(block_id=clause.node_id),
                    ))
                seen_nodes.add(clause.node_id)
                if depth > MAX_CLAUSE_DEPTH:
                    diagnostics.append(Diagnostic(
                        code="CLAUSE_DEPTH_EXCEEDED",
                        severity="error",
                        message=f"clause 层级超过 {MAX_CLAUSE_DEPTH}: {clause.node_id}",
                        location=DiagnosticLocation(block_id=clause.node_id),
                    ))
                _walk(clause.children, depth + 1)

        for _section, block in _iter_blocks(state.document):
            clauses = getattr(block, "clauses", None)
            if clauses:
                _walk(clauses, 1)
        return _result(diagnostics)


class ActionValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        finding_ids = {f.finding_id for f in state.document.findings}
        seen_actions: set[str] = set()
        for action in state.document.actions:
            if action.action_id in seen_actions:
                diagnostics.append(Diagnostic(
                    code="ACTION_ID_DUPLICATE",
                    severity="error",
                    message=f"重复的 action_id: {action.action_id}",
                    location=DiagnosticLocation(field="actions"),
                ))
            seen_actions.add(action.action_id)
            for ref in action.finding_refs:
                if ref not in finding_ids:
                    diagnostics.append(Diagnostic(
                        code="ACTION_FINDING_REF_NOT_REGISTERED",
                        severity="error",
                        message=f"action 引用未注册的 finding: {ref}",
                        location=DiagnosticLocation(field="actions"),
                    ))
        return _result(diagnostics)


class BodyContentValidationPass(CompilerPass):
    """task068 T10 — reject raw JSON / absolute paths in body text.

    Body blocks (paragraph/claim/list/key-value/table/warning/clause) and
    finding statement/recommendation/suggested-revision text must be semantic
    prose, never a serialized request payload, a storage URI, or a filesystem
    path. The adapter sanitizes these upstream (T09); this pass is the
    fail-closed backstop so a regression is caught before any renderer runs.
    """

    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []

        def _check(text: str, *, section_id: str, block_id: str | None = None) -> None:
            if not text:
                return
            location = DiagnosticLocation(section_id=section_id, block_id=block_id)
            if _RAW_JSON_OBJECT_RE.search(text) or _RAW_JSON_ARRAY_RE.search(text):
                diagnostics.append(Diagnostic(
                    code="BODY_RAW_JSON",
                    severity="error",
                    message="正文包含原始 JSON 对象/数组，必须映射为语义 block",
                    location=location,
                ))
            if _ABS_PATH_RE.search(text):
                diagnostics.append(Diagnostic(
                    code="BODY_ABSOLUTE_PATH",
                    severity="error",
                    message="正文包含绝对路径/URI，不得泄漏到正式正文",
                    location=location,
                ))
            if _DEBUG_FIELD_RE.search(text):
                diagnostics.append(Diagnostic(
                    code="BODY_DEBUG_FIELD",
                    severity="error",
                    message="正文包含原始请求字段名/调试字段，必须映射为语义值",
                    location=location,
                ))

        for section in state.document.sections:
            for block in section.blocks:
                text = getattr(block, "text", None)
                if text:
                    _check(text, section_id=section.section_id, block_id=block.block_id)
                for item in getattr(block, "items", []):
                    _check(getattr(item, "text", None), section_id=section.section_id, block_id=block.block_id)
                    _check(getattr(item, "label", None), section_id=section.section_id, block_id=block.block_id)
                    _check(getattr(item, "value", None), section_id=section.section_id, block_id=block.block_id)
                for row in getattr(block, "rows", []):
                    for cell in row:
                        _check(cell, section_id=section.section_id, block_id=block.block_id)
                clauses = getattr(block, "clauses", [])
                for clause in _iter_clause_nodes(clauses):
                    _check(clause.text, section_id=section.section_id, block_id=block.block_id)

        for finding in state.document.findings:
            for text in (finding.statement, finding.recommendation, finding.suggested_revision):
                _check(text, section_id="findings")
            for basis in finding.basis_entries:
                _check(basis.rationale, section_id="findings")

        return _result(diagnostics)


class RenderContractValidationPass(CompilerPass):
    def run(self, state: CompilerState) -> PassResult:
        diagnostics: list[Diagnostic] = []
        profile_id = state.document.render_contract.profile_id
        if profile_id not in KNOWN_PROFILE_IDS:
            diagnostics.append(Diagnostic(
                code="RENDER_PROFILE_UNKNOWN",
                severity="fatal",
                message=f"未知 render profile: {profile_id}",
                location=DiagnosticLocation(field="render_contract"),
            ))
        return _result(diagnostics)


class DocumentCompiler:
    """Run the v4 passes in deterministic order."""

    def __init__(self, passes: list[CompilerPass] | None = None) -> None:
        self.passes = passes or [
            InputValidationPass(),
            FindingValidationPass(),
            BasisValidationPass(),
            ClauseStructureValidationPass(),
            ActionValidationPass(),
            CitationValidationPass(),
            CitationNumberingPass(),
            DedupValidationPass(),
            StructureValidationPass(),
            BodyContentValidationPass(),
            RenderContractValidationPass(),
            RenderValidationPass(),
        ]

    def compile(
        self,
        document: DocumentIR,
        registry: CitationRegistry | None = None,
        *,
        rendered_text: str = "",
    ) -> CompileResult:
        if registry is None:
            registry = CitationRegistry(document.citations)
        state = CompilerState(document=document, registry=registry, rendered_text=rendered_text)
        for compiler_pass in self.passes:
            result = compiler_pass.run(state)
            state.diagnostics.extend(result.diagnostics)
            if result.status == "fatal":
                break
        state.document.diagnostics = state.diagnostics
        status = "fatal" if any(d.severity == "fatal" for d in state.diagnostics) else (
            "error" if any(d.severity == "error" for d in state.diagnostics) else "success"
        )
        return CompileResult(status=status, document=state.document, diagnostics=tuple(state.diagnostics))
