import { useEffect, useMemo, useState } from "react";
import { fetchArtifactPreview, type ArtifactPreview } from "../../lib/artifact-preview";
import { CitationMarkdownRenderer } from "../citation/CitationMarkdownRenderer";

type IntermediatesSubTab =
  | "facts"
  | "path_judgment"
  | "issues"
  | "gaps"
  | "evidence"
  | "spi"
  | "vendor"
  | "materials"
  | "report";

interface SubTabDef {
  id: IntermediatesSubTab;
  labelZh: string;
  labelEn: string;
  fileKey: string;
}

const SUB_TABS: SubTabDef[] = [
  { id: "facts", labelZh: "事实识别", labelEn: "Facts", fileKey: "facts_json" },
  { id: "path_judgment", labelZh: "路径判断", labelEn: "Path Judgment", fileKey: "path_judgment_json" },
  { id: "issues", labelZh: "问题清单", labelEn: "Issue List", fileKey: "issue_list_json" },
  { id: "gaps", labelZh: "差距项", labelEn: "Gap Items", fileKey: "gap_items_json" },
  { id: "evidence", labelZh: "证据链", labelEn: "Evidence Chain", fileKey: "evidence_chain_json" },
  { id: "spi", labelZh: "敏感信息风险", labelEn: "SPI Risks", fileKey: "spi_risks_json" },
  { id: "vendor", labelZh: "供应商问题", labelEn: "Vendor Issues", fileKey: "vendor_issues_json" },
  { id: "materials", labelZh: "材料清单", labelEn: "Material Checklist", fileKey: "material_checklist_json" },
  { id: "report", labelZh: "报告输出", labelEn: "Report Output", fileKey: "markdown" },
];

interface Props {
  outputFiles: Record<string, string>;
  lang: "zh" | "en";
}

type TabState = {
  loading: boolean;
  error: string | null;
  preview: ArtifactPreview | null;
  data: unknown;
};

const EMPTY_TAB_STATE: TabState = { loading: false, error: null, preview: null, data: null };

const MISSING_ZH = "当前模块尚未生成该中间产物。";
const MISSING_EN = "This intermediate artifact has not been generated by the current module.";

function label(tab: SubTabDef, lang: "zh" | "en"): string {
  return lang === "zh" ? tab.labelZh : tab.labelEn;
}

export function AssessmentIntermediatesPanel({ outputFiles, lang }: Props) {
  const [activeSubTab, setActiveSubTab] = useState<IntermediatesSubTab>("issues");
  const [tabStates, setTabStates] = useState<Record<string, TabState>>({});

  const activeDef = useMemo(() => SUB_TABS.find((t) => t.id === activeSubTab)!, [activeSubTab]);
  const activeState: TabState = tabStates[activeSubTab] ?? EMPTY_TAB_STATE;

  const filePath = outputFiles[activeDef.fileKey];

  useEffect(() => {
    if (!filePath) {
      setTabStates((prev) => ({
        ...prev,
        [activeSubTab]: { loading: false, error: null, preview: null, data: null },
      }));
      return;
    }

    let cancelled = false;
    setTabStates((prev) => ({
      ...prev,
      [activeSubTab]: { ...EMPTY_TAB_STATE, loading: true },
    }));

    fetchArtifactPreview(filePath)
      .then((preview) => {
        if (cancelled) return;
        let data: unknown = null;
        if (preview.render_mode === "text" && preview.content) {
          try {
            data = JSON.parse(preview.content);
          } catch {
            data = null;
          }
        }
        setTabStates((prev) => ({
          ...prev,
          [activeSubTab]: { loading: false, error: null, preview, data },
        }));
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setTabStates((prev) => ({
          ...prev,
          [activeSubTab]: {
            loading: false,
            error: err instanceof Error ? err.message : String(err),
            preview: null,
            data: null,
          },
        }));
      });

    return () => {
      cancelled = true;
    };
  }, [activeSubTab, filePath]);

  return (
    <section className="assessment-intermediates">
      <nav className="assessment-intermediates-tabs">
        {SUB_TABS.map((tab) => (
          <button
            key={tab.id}
            className={`assessment-intermediates-tab ${activeSubTab === tab.id ? "active" : ""}`}
            onClick={() => setActiveSubTab(tab.id)}
          >
            {label(tab, lang)}
          </button>
        ))}
      </nav>

      <div className="assessment-intermediates-body">
        {!filePath ? (
          <div className="assessment-intermediates-empty">
            <p>{lang === "zh" ? MISSING_ZH : MISSING_EN}</p>
          </div>
        ) : activeState.loading ? (
          <div className="assessment-intermediates-empty">
            <p>{lang === "zh" ? "正在加载..." : "Loading..."}</p>
          </div>
        ) : activeState.error ? (
          <div className="assessment-intermediates-empty assessment-intermediates-error">
            <p>{activeState.error}</p>
          </div>
        ) : activeSubTab === "report" ? (
          <ReportTab preview={activeState.preview} lang={lang} filePath={filePath} />
        ) : (
          <DataTab tabId={activeSubTab} data={activeState.data} lang={lang} />
        )}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Report tab — renders markdown content with interactive citation markers
// ---------------------------------------------------------------------------

function extractTaskId(filePath: string | undefined): string | null {
  if (!filePath) return null;
  const match = filePath.match(/outputs\/assessment\/([a-f0-9-]+)/i);
  return match ? match[1] : null;
}

function ReportTab({ preview, lang, filePath }: { preview: ArtifactPreview | null; lang: "zh" | "en"; filePath?: string }) {
  const taskId = extractTaskId(filePath);

  if (!preview || !preview.content) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? "报告内容暂未生成。" : "Report content not yet generated."}</p>
      </div>
    );
  }

  if (!taskId) {
    return (
      <article className="assessment-intermediates-report">
        <pre className="assessment-intermediates-markdown">{preview.content}</pre>
      </article>
    );
  }

  return (
    <article className="assessment-intermediates-report">
      <CitationMarkdownRenderer markdown={preview.content} taskId={taskId} moduleKey="assessment" />
    </article>
  );
}

// ---------------------------------------------------------------------------
// Data tab — renders structured table from parsed JSON
// ---------------------------------------------------------------------------

type ColumnDef = {
  key: string;
  labelZh: string;
  labelEn: string;
  render?: (value: unknown) => string;
};

function joinIfArray(value: unknown): string {
  if (Array.isArray(value)) return value.map(String).join("; ");
  if (value === null || value === undefined) return "-";
  return String(value);
}

function severityBadge(severity: string): string {
  const s = severity.toUpperCase();
  if (s === "BLOCKER") return "🔴 " + severity;
  if (s === "HIGH") return "🟠 " + severity;
  if (s === "MEDIUM") return "🟡 " + severity;
  return "🟢 " + severity;
}

const COLUMNS: Record<string, ColumnDef[]> = {
  facts: [
    { key: "fact_id", labelZh: "编号", labelEn: "ID" },
    { key: "source_type", labelZh: "来源类型", labelEn: "Source Type" },
    { key: "field_path", labelZh: "字段路径", labelEn: "Field Path" },
    { key: "value", labelZh: "值", labelEn: "Value" },
    { key: "confidence", labelZh: "置信度", labelEn: "Confidence" },
  ],
  path_judgment: [
    { key: "recommended_path", labelZh: "推荐路径", labelEn: "Recommended Path" },
    { key: "risk_level", labelZh: "风险等级", labelEn: "Risk Level" },
    { key: "rationale", labelZh: "依据", labelEn: "Rationale" },
    { key: "path_warning", labelZh: "路径警告", labelEn: "Path Warning", render: (v) => (v ? String(v) : "-") },
    { key: "is_override", labelZh: "强制覆盖", labelEn: "Force Override", render: (v) => (v ? "是" : "否") },
  ],
  issues: [
    { key: "issue_id", labelZh: "编号", labelEn: "ID" },
    { key: "severity", labelZh: "严重度", labelEn: "Severity", render: (v) => severityBadge(String(v)) },
    { key: "title", labelZh: "标题", labelEn: "Title" },
    { key: "category", labelZh: "类别", labelEn: "Category" },
    { key: "recommended_action", labelZh: "建议措施", labelEn: "Recommended Action" },
    { key: "fact_refs", labelZh: "关联事实", labelEn: "Related Facts", render: joinIfArray },
    { key: "rule_refs", labelZh: "关联规则", labelEn: "Related Rules", render: joinIfArray },
  ],
  evidence: [
    { key: "evidence_id", labelZh: "编号", labelEn: "ID" },
    { key: "claim", labelZh: "主张", labelEn: "Claim" },
    { key: "conclusion", labelZh: "结论", labelEn: "Conclusion" },
    { key: "confidence", labelZh: "置信度", labelEn: "Confidence" },
    { key: "fact_refs", labelZh: "关联事实", labelEn: "Related Facts", render: joinIfArray },
    { key: "rule_refs", labelZh: "关联规则", labelEn: "Related Rules", render: joinIfArray },
    { key: "used_by", labelZh: "被使用于", labelEn: "Used By", render: joinIfArray },
  ],
  gaps: [
    { key: "domain", labelZh: "领域", labelEn: "Domain" },
    { key: "risk_level", labelZh: "风险等级", labelEn: "Risk", render: (v) => severityBadge(String(v)) },
    { key: "gap", labelZh: "差距描述", labelEn: "Gap" },
    { key: "legal_basis", labelZh: "法律依据", labelEn: "Legal Basis" },
    { key: "recommendation", labelZh: "建议", labelEn: "Recommendation" },
    { key: "phase", labelZh: "阶段", labelEn: "Phase" },
  ],
  spi: [
    { key: "category", labelZh: "类别", labelEn: "Category" },
    { key: "is_sensitive", labelZh: "是否敏感", labelEn: "Sensitive" },
    { key: "risk_level", labelZh: "风险等级", labelEn: "Risk" },
  ],
  vendor: [
    { key: "name", labelZh: "供应商名", labelEn: "Vendor" },
    { key: "vendor_type", labelZh: "类型", labelEn: "Type" },
    { key: "receives_spi", labelZh: "接收SPI", labelEn: "Receives SPI" },
    { key: "risk_level", labelZh: "风险等级", labelEn: "Risk" },
  ],
  materials: [
    { key: "source_ref", labelZh: "材料编号", labelEn: "Source Ref" },
    { key: "summary", labelZh: "摘要", labelEn: "Summary" },
    { key: "status", labelZh: "状态", labelEn: "Status" },
  ],
};

function DataTab({ tabId, data, lang }: { tabId: IntermediatesSubTab; data: unknown; lang: "zh" | "en" }) {
  if (tabId === "issues") {
    return <IssueTab data={data} lang={lang} />;
  }

  const columns = COLUMNS[tabId] ?? [];

  if (!data) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? MISSING_ZH : MISSING_EN}</p>
      </div>
    );
  }

  const rows: Record<string, unknown>[] = Array.isArray(data) ? data : [data];

  if (rows.length === 0) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? "数据为空。" : "No data available."}</p>
      </div>
    );
  }

  return (
    <div className="assessment-intermediates-table-wrap">
      <table className="assessment-intermediates-table">
        <thead>
          <tr>
            <th>#</th>
            {columns.map((col) => (
              <th key={col.key}>{lang === "zh" ? col.labelZh : col.labelEn}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, idx) => (
            <tr key={idx}>
              <td className="assessment-intermediates-row-num">{idx + 1}</td>
              {columns.map((col) => {
                const raw = row[col.key];
                const display = col.render ? col.render(raw) : joinIfArray(raw);
                return <td key={col.key}>{display}</td>;
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

type IssueRow = {
  issue_id?: string;
  severity?: string;
  title?: string;
  description?: string;
  category?: string;
  recommended_action?: string;
  fact_refs?: string[];
  rule_refs?: string[];
  evidence_refs?: string[];
};

function IssueTab({ data, lang }: { data: unknown; lang: "zh" | "en" }) {
  const rows: IssueRow[] = Array.isArray(data) ? (data as IssueRow[]) : [];
  const [selectedIssueId, setSelectedIssueId] = useState<string | null>(rows[0]?.issue_id ?? null);

  useEffect(() => {
    setSelectedIssueId(rows[0]?.issue_id ?? null);
  }, [data]);

  if (!rows.length) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? MISSING_ZH : MISSING_EN}</p>
      </div>
    );
  }

  const selectedIssue = rows.find((row) => row.issue_id === selectedIssueId) ?? rows[0];
  const issueTitle = selectedIssue.title || selectedIssue.issue_id || "-";

  return (
    <div className="assessment-intermediates-issue-layout">
      <div className="assessment-intermediates-table-wrap">
        <table className="assessment-intermediates-table">
          <thead>
            <tr>
              <th>#</th>
              {COLUMNS.issues.map((col) => (
                <th key={col.key}>{lang === "zh" ? col.labelZh : col.labelEn}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, idx) => {
              const isSelected = row.issue_id === selectedIssue.issue_id;
              return (
                <tr
                  key={row.issue_id ?? idx}
                  className={isSelected ? "assessment-intermediates-row-active" : ""}
                  onClick={() => setSelectedIssueId(row.issue_id ?? null)}
                >
                  <td className="assessment-intermediates-row-num">{idx + 1}</td>
                  {COLUMNS.issues.map((col) => {
                    const raw = row[col.key as keyof IssueRow];
                    const display = col.render ? col.render(raw) : joinIfArray(raw);
                    return <td key={col.key}>{display}</td>;
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <aside className="assessment-intermediates-issue-detail">
        <header>
          <span>{lang === "zh" ? "问题详情" : "Issue Detail"}</span>
          <strong>{issueTitle}</strong>
        </header>
        <dl>
          <div>
            <dt>{lang === "zh" ? "问题编号" : "Issue ID"}</dt>
            <dd>{selectedIssue.issue_id || "-"}</dd>
          </div>
          <div>
            <dt>{lang === "zh" ? "描述" : "Description"}</dt>
            <dd>{selectedIssue.description || "-"}</dd>
          </div>
          <div>
            <dt>{lang === "zh" ? "建议措施" : "Recommended Action"}</dt>
            <dd>{selectedIssue.recommended_action || "-"}</dd>
          </div>
          <div>
            <dt>{lang === "zh" ? "关联事实" : "Related Facts"}</dt>
            <dd>{joinIfArray(selectedIssue.fact_refs)}</dd>
          </div>
          <div>
            <dt>{lang === "zh" ? "关联规则" : "Related Rules"}</dt>
            <dd>{joinIfArray(selectedIssue.rule_refs)}</dd>
          </div>
          <div>
            <dt>{lang === "zh" ? "关联证据" : "Related Evidence"}</dt>
            <dd>{joinIfArray(selectedIssue.evidence_refs)}</dd>
          </div>
        </dl>
      </aside>
    </div>
  );
}
