import { useEffect, useMemo, useState } from "react";
import { fetchArtifactPreview, type ArtifactPreview } from "../../lib/artifact-preview";

type IntermediatesSubTab =
  | "facts"
  | "path_judgment"
  | "issues"
  | "evidence"
  | "materials"
  | "report";

interface SubTabDef {
  id: IntermediatesSubTab;
  labelZh: string;
  labelEn: string;
  fileKey: string;
}

const SUB_TABS: SubTabDef[] = [
  { id: "facts", labelZh: "事实识别", labelEn: "Facts", fileKey: "facts_json" },
  { id: "path_judgment", labelZh: "路径判断", labelEn: "Path Judgment", fileKey: "path_judgment_json" },
  { id: "issues", labelZh: "问题清单", labelEn: "Issue List", fileKey: "issue_list_json" },
  { id: "evidence", labelZh: "证据链", labelEn: "Evidence Chain", fileKey: "evidence_chain_json" },
  { id: "materials", labelZh: "材料清单", labelEn: "Material Checklist", fileKey: "material_checklist_json" },
  { id: "report", labelZh: "报告输出", labelEn: "Report Output", fileKey: "markdown" },
];

interface Props {
  outputFiles: Record<string, string>;
  lang: "zh" | "en";
}

type TabState = {
  loading: boolean;
  error: string | null;
  preview: ArtifactPreview | null;
  data: unknown;
};

const EMPTY_TAB_STATE: TabState = { loading: false, error: null, preview: null, data: null };

const MISSING_ZH = "当前模块尚未生成该中间产物。";
const MISSING_EN = "This intermediate artifact has not been generated by the current module.";

function label(tab: SubTabDef, lang: "zh" | "en"): string {
  return lang === "zh" ? tab.labelZh : tab.labelEn;
}

export function AssessmentIntermediatesPanel({ outputFiles, lang }: Props) {
  const [activeSubTab, setActiveSubTab] = useState<IntermediatesSubTab>("issues");
  const [tabStates, setTabStates] = useState<Record<string, TabState>>({});

  const activeDef = useMemo(() => SUB_TABS.find((t) => t.id === activeSubTab)!, [activeSubTab]);
  const activeState: TabState = tabStates[activeSubTab] ?? EMPTY_TAB_STATE;

  const filePath = outputFiles[activeDef.fileKey];

  useEffect(() => {
    if (!filePath) {
      setTabStates((prev) => ({
        ...prev,
        [activeSubTab]: { loading: false, error: null, preview: null, data: null },
      }));
      return;
    }

    let cancelled = false;
    setTabStates((prev) => ({
      ...prev,
      [activeSubTab]: { ...EMPTY_TAB_STATE, loading: true },
    }));

    fetchArtifactPreview(filePath)
      .then((preview) => {
        if (cancelled) return;
        let data: unknown = null;
        if (preview.render_mode === "text" && preview.content) {
          try {
            data = JSON.parse(preview.content);
          } catch {
            data = null;
          }
        }
        setTabStates((prev) => ({
          ...prev,
          [activeSubTab]: { loading: false, error: null, preview, data },
        }));
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setTabStates((prev) => ({
          ...prev,
          [activeSubTab]: {
            loading: false,
            error: err instanceof Error ? err.message : String(err),
            preview: null,
            data: null,
          },
        }));
      });

    return () => {
      cancelled = true;
    };
  }, [activeSubTab, filePath]);

  return (
    <section className="assessment-intermediates">
      <nav className="assessment-intermediates-tabs">
        {SUB_TABS.map((tab) => (
          <button
            key={tab.id}
            className={`assessment-intermediates-tab ${activeSubTab === tab.id ? "active" : ""}`}
            onClick={() => setActiveSubTab(tab.id)}
          >
            {label(tab, lang)}
          </button>
        ))}
      </nav>

      <div className="assessment-intermediates-body">
        {!filePath ? (
          <div className="assessment-intermediates-empty">
            <p>{lang === "zh" ? MISSING_ZH : MISSING_EN}</p>
          </div>
        ) : activeState.loading ? (
          <div className="assessment-intermediates-empty">
            <p>{lang === "zh" ? "正在加载..." : "Loading..."}</p>
          </div>
        ) : activeState.error ? (
          <div className="assessment-intermediates-empty assessment-intermediates-error">
            <p>{activeState.error}</p>
          </div>
        ) : activeSubTab === "report" ? (
          <ReportTab preview={activeState.preview} lang={lang} />
        ) : (
          <DataTab tabId={activeSubTab} data={activeState.data} lang={lang} />
        )}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Report tab — renders markdown content
// ---------------------------------------------------------------------------

function ReportTab({ preview, lang }: { preview: ArtifactPreview | null; lang: "zh" | "en" }) {
  if (!preview || !preview.content) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? "报告内容暂未生成。" : "Report content not yet generated."}</p>
      </div>
    );
  }

  return (
    <article className="assessment-intermediates-report">
      <pre className="assessment-intermediates-markdown">{preview.content}</pre>
    </article>
  );
}

// ---------------------------------------------------------------------------
// Data tab — renders structured table from parsed JSON
// ---------------------------------------------------------------------------

type ColumnDef = {
  key: string;
  labelZh: string;
  labelEn: string;
  render?: (value: unknown) => string;
};

function joinIfArray(value: unknown): string {
  if (Array.isArray(value)) return value.map(String).join("; ");
  if (value === null || value === undefined) return "-";
  return String(value);
}

function severityBadge(severity: string): string {
  const s = severity.toUpperCase();
  if (s === "BLOCKER") return "🔴 " + severity;
  if (s === "HIGH") return "🟠 " + severity;
  if (s === "MEDIUM") return "🟡 " + severity;
  return "🟢 " + severity;
}

const COLUMNS: Record<string, ColumnDef[]> = {
  facts: [
    { key: "fact_id", labelZh: "编号", labelEn: "ID" },
    { key: "source_type", labelZh: "来源类型", labelEn: "Source Type" },
    { key: "field_path", labelZh: "字段路径", labelEn: "Field Path" },
    { key: "value", labelZh: "值", labelEn: "Value" },
    { key: "confidence", labelZh: "置信度", labelEn: "Confidence" },
  ],
  path_judgment: [
    { key: "recommended_path", labelZh: "推荐路径", labelEn: "Recommended Path" },
    { key: "risk_level", labelZh: "风险等级", labelEn: "Risk Level" },
    { key: "rationale", labelZh: "依据", labelEn: "Rationale" },
    { key: "path_warning", labelZh: "路径警告", labelEn: "Path Warning", render: (v) => (v ? String(v) : "-") },
    { key: "is_override", labelZh: "强制覆盖", labelEn: "Force Override", render: (v) => (v ? "是" : "否") },
  ],
  issues: [
    { key: "issue_id", labelZh: "编号", labelEn: "ID" },
    { key: "severity", labelZh: "严重度", labelEn: "Severity", render: (v) => severityBadge(String(v)) },
    { key: "title", labelZh: "标题", labelEn: "Title" },
    { key: "category", labelZh: "类别", labelEn: "Category" },
    { key: "recommended_action", labelZh: "建议措施", labelEn: "Recommended Action" },
    { key: "fact_refs", labelZh: "关联事实", labelEn: "Related Facts", render: joinIfArray },
    { key: "rule_refs", labelZh: "关联规则", labelEn: "Related Rules", render: joinIfArray },
  ],
  evidence: [
    { key: "evidence_id", labelZh: "编号", labelEn: "ID" },
    { key: "claim", labelZh: "主张", labelEn: "Claim" },
    { key: "conclusion", labelZh: "结论", labelEn: "Conclusion" },
    { key: "confidence", labelZh: "置信度", labelEn: "Confidence" },
    { key: "fact_refs", labelZh: "关联事实", labelEn: "Related Facts", render: joinIfArray },
    { key: "rule_refs", labelZh: "关联规则", labelEn: "Related Rules", render: joinIfArray },
    { key: "used_by", labelZh: "被使用于", labelEn: "Used By", render: joinIfArray },
  ],
  materials: [
    { key: "source_ref", labelZh: "材料编号", labelEn: "Source Ref" },
    { key: "summary", labelZh: "摘要", labelEn: "Summary" },
    { key: "status", labelZh: "状态", labelEn: "Status" },
  ],
};

function DataTab({ tabId, data, lang }: { tabId: IntermediatesSubTab; data: unknown; lang: "zh" | "en" }) {
  const columns = COLUMNS[tabId] ?? [];

  if (!data) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? MISSING_ZH : MISSING_EN}</p>
      </div>
    );
  }

  const rows: Record<string, unknown>[] = Array.isArray(data) ? data : [data];

  if (rows.length === 0) {
    return (
      <div className="assessment-intermediates-empty">
        <p>{lang === "zh" ? "数据为空。" : "No data available."}</p>
      </div>
    );
  }

  return (
    <div className="assessment-intermediates-table-wrap">
      <table className="assessment-intermediates-table">
        <thead>
          <tr>
            <th>#</th>
            {columns.map((col) => (
              <th key={col.key}>{lang === "zh" ? col.labelZh : col.labelEn}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, idx) => (
            <tr key={idx}>
              <td className="assessment-intermediates-row-num">{idx + 1}</td>
              {columns.map((col) => {
                const raw = row[col.key];
                const display = col.render ? col.render(raw) : joinIfArray(raw);
                return <td key={col.key}>{display}</td>;
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
