<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>马来西亚数据跨境与数据保护核心法规目录</title><style>body{margin:0;background:#f4f6f8;color:#172033;font:15px/1.7 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}main{max-width:980px;margin:0 auto;padding:42px 24px 72px}header{background:linear-gradient(135deg,#123c69,#16697a);color:#fff;padding:34px;border-radius:18px;box-shadow:0 10px 32px #123c6922}h1{margin:0 0 8px;font-size:30px}header p{margin:6px 0;color:#edf7fa}nav{margin:22px 0}nav a{display:inline-block;margin-right:10px;padding:7px 14px;border-radius:999px;background:#fff;color:#125b78;text-decoration:none;border:1px solid #d6e1e8}h2{margin-top:38px;border-bottom:2px solid #d7e3e9;padding-bottom:7px;color:#123c69}.card{background:#fff;border:1px solid #dce5ea;border-radius:14px;padding:20px 22px;margin:14px 0;box-shadow:0 4px 18px #2030400b}.card h3{margin:3px 0 11px;font-size:19px}.card p{margin:7px 0}.code{font-size:13px;color:#53697c}a{color:#096a91}a.local{display:inline-block;background:#126b84;color:#fff;text-decoration:none;padding:6px 12px;border-radius:8px}.notice{background:#fff6db;border-left:5px solid #d4a017;padding:16px 18px;margin:22px 0;border-radius:8px}footer{margin-top:40px;color:#647487;font-size:13px}</style></head><body><main>
<header><h1>马来西亚数据跨境与数据保护核心法规原文</h1><p>数规通知识库入库包 · 官方来源核验版</p><p>核验与下载日期：2026-07-29　共8份官方PDF</p></header>
<div class="notice"><b>收录口径：</b>仅收录一般个人数据保护、跨境传输、数据泄露，以及国家关键信息基础设施网络安全的核心、现行且有法律约束力的文件。未收录指南、通告、行业守则、反黑客／电子商务法及单纯收费、登记、罚款程序文件。<br><b>重要提示：</b>A01 为官网2022基础法文本；A02（2024修正法）和A03（生效公告）均须与其合并阅读，才能反映截至核验日的现行法律状态。全部PDF均由JPDP或马来西亚总检察署Laws of Malaysia系统直接下载。</div>
<nav><a href="#A">A. 个人数据保护与跨境传输</a><a href="#B">B. 网络安全与国家关键信息基础设施</a></nav>
<h2 id="A">A. 个人数据保护与跨境传输</h2>
<article class="card"><div class="code">A01 · 法律／基础法文本</div><h3>Personal Data Protection Act 2010 [Act 709]（《个人数据保护法 2010》）</h3><p><b>效力／状态：</b>现行；本地PDF为2022基础法版本，须与A02、A03合并使用。</p><p><b>使用提示：</b>商业交易中个人数据处理的一般基本法。</p><p><a class="local" href="A01_Personal%20Data%20Protection%20Act%202010_个人数据保护法_基础法官方文本_2022版.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://www.pdp.gov.my/ppdpv1/en/akta/pdp-act-2010-en/" target="_blank" rel="noopener">JPDP官方来源</a></p></article>
<article class="card"><div class="code">A02 · 法律／修正法</div><h3>Personal Data Protection (Amendment) Act 2024 [Act A1727]（《个人数据保护（修正）法 2024》）</h3><p><b>效力／状态：</b>已全部生效。</p><p><b>使用提示：</b>修正A01，包括跨境传输、数据泄露通知等关键制度。</p><p><a class="local" href="A02_Personal%20Data%20Protection%20%28Amendment%29%20Act%202024_个人数据保护修正法_全条已生效.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://www.pdp.gov.my/ppdpv1/en/akta/personal-data-protection-amendment-act-2024/" target="_blank" rel="noopener">JPDP官方来源</a></p></article>
<article class="card"><div class="code">A03 · 联邦政府公报／生效公告</div><h3>Personal Data Protection (Amendment) Act 2024 — Appointment of Date of Coming into Operation [P.U. (B) 522]</h3><p><b>效力／状态：</b>现行；于2025-01-01、2025-04-01及2025-06-01分阶段使A02全部条款生效。</p><p><b>使用提示：</b>确认A02并非“已颁布未施行”的官方公报。</p><p><a class="local" href="A03_Personal%20Data%20Protection%20%28Amendment%29%20Act%202024_Appointment%20of%20Date%20of%20Coming%20into%20Operation_生效日期公告_PU%28B%29522.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://www.pdp.gov.my/ppdpv1/wp-content/uploads/2024/12/PENETAPAN-TARIKH-PERMULAAN-KUAT-KUASA.pdf" target="_blank" rel="noopener">官方公报来源</a></p></article>
<article class="card"><div class="code">A04 · 实施条例</div><h3>Personal Data Protection Regulations 2013 [P.U. (A) 335]（《个人数据保护条例 2013》）</h3><p><b>效力／状态：</b>现行；2025年仅有拟修正征求意见，尚未形成新法。</p><p><b>使用提示：</b>法定实施条例，包含数据保护标准的制定依据及执行性要求。</p><p><a class="local" href="A04_Personal%20Data%20Protection%20Regulations%202013_个人数据保护条例_PU%28A%29335.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://www.pdp.gov.my/ppdpv1/en/akta/personal-data-protection-regulations-2013/" target="_blank" rel="noopener">JPDP官方来源</a></p></article>
<article class="card"><div class="code">A05 · 法定标准</div><h3>Personal Data Protection Standard 2015（《个人数据保护标准 2015》）</h3><p><b>效力／状态：</b>现行法定标准；“标准2025”仍处于征求意见，未取代本文件。</p><p><b>使用提示：</b>规定安全、保存期限与数据完整性的具体最低要求；不是一般指导文件。</p><p><a class="local" href="A05_Personal%20Data%20Protection%20Standard%202015_个人数据保护标准_现行法定标准.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://www.pdp.gov.my/ppdpv1/en/akta/personal-data-protection-standard-2015/" target="_blank" rel="noopener">JPDP官方来源</a></p></article>
<h2 id="B">B. 网络安全与国家关键信息基础设施</h2>
<article class="card"><div class="code">B01 · 法律</div><h3>Cyber Security Act 2024 [Act 854]（《网络安全法 2024》）</h3><p><b>效力／状态：</b>现行；2024-08-26生效。</p><p><b>使用提示：</b>建立国家关键信息基础设施（NCII）网络安全、事件管理及监管框架。</p><p><a class="local" href="B01_Cyber%20Security%20Act%202024_网络安全法_Act854.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://lom.agc.gov.my/act-detail.php?language=BI&amp;act=854" target="_blank" rel="noopener">总检察署官方来源</a></p></article>
<article class="card"><div class="code">B02 · 实施条例／事件通报</div><h3>Cyber Security (Notification of Cyber Security Incident) Regulations 2024 [P.U. (A) 220]</h3><p><b>效力／状态：</b>现行；2024-08-26生效。</p><p><b>使用提示：</b>针对NCII实体的网络安全事件通知规则。</p><p><a class="local" href="B02_Cyber%20Security%20%28Notification%20of%20Cyber%20Security%20Incident%29%20Regulations%202024_网络安全事件通知条例_PU%28A%29220.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://nacsa.gov.my/legal.php" target="_blank" rel="noopener">NACSA官方来源</a></p></article>
<article class="card"><div class="code">B03 · 实施条例／风险评估与审计</div><h3>Cyber Security (Period for Cyber Security Risk Assessment and Audit) Regulations 2024 [P.U. (A) 219]</h3><p><b>效力／状态：</b>现行；2024-08-26生效。</p><p><b>使用提示：</b>规定NCII实体进行网络安全风险评估和审计的法定周期。</p><p><a class="local" href="B03_Cyber%20Security%20%28Period%20for%20Cyber%20Security%20Risk%20Assessment%20and%20Audit%29%20Regulations%202024_网络安全风险评估和审计期限条例_PU%28A%29219.pdf" target="_blank">打开本地官方PDF</a>　<a href="https://nacsa.gov.my/legal.php" target="_blank" rel="noopener">NACSA官方来源</a></p></article>
<footer>本目录用于法规资料识别与知识库建设，不构成针对具体事项的法律意见。文件已逐份核验为PDF格式、页数及首页标题，并保留官方来源链接供后续复核。</footer>
</main></body></html>
