"""Schema-first reporting primitives (v4).

The package is additive during the migration. Existing Markdown renderers keep
their current behavior until a compiler feature flag is explicitly enabled.
v4 adds the finding / clause / render-contract block and record types without
changing the v3 constructor surface, so existing schema-first adapters compile
unchanged.
"""

from backend.common.reporting.compiler import (
    CompileResult,
    DocumentCompiler,
    PassResult,
)
from backend.common.reporting.compat import (
    extract_citation_refs,
    legacy_item_to_record,
    legacy_registry_to_reporting,
)
from backend.common.reporting.migration import migrate_v3_document
from backend.common.reporting.render_manifest import (
    ArtifactRecord,
    ClauseIdentity,
    DocxStats,
    FontRecord,
    GateResult,
    PdfStats,
    RenderManifest,
    build_render_manifest,
    verify_render_manifest,
)
from backend.common.reporting.renderers import (
    DocxRenderer,
    DocxRenderError,
    FontSpec,
    MarkdownRenderer,
    PdfRenderer,
    PdfRenderError,
    RenderError,
    render_docx,
    render_docx_to_file,
    render_markdown,
    render_pdf,
    render_pdf_to_file,
)
from backend.common.reporting.shadow_render import (
    CollectionAudit,
    RenderingMode,
    audit_ir_vs_legacy,
    render_ir_artifacts,
    write_audit_json,
)
from backend.common.reporting.schema import (
    ActionRecord,
    Block,
    CitationLocator,
    CitationNoteBlock,
    CitationRecord,
    CitationRegistry,
    ClaimBlock,
    ClauseGroupBlock,
    ClauseNode,
    Diagnostic,
    DiagnosticLocation,
    DocumentIR,
    FindingBasis,
    FindingDetailBlock,
    FindingRecord,
    FindingReferenceBlock,
    FindingSummaryBlock,
    Identity,
    Integrity,
    KeyValueBlock,
    KeyValueItem,
    Lifecycle,
    ListBlock,
    ListItem,
    NumberingStyle,
    PageBreakBlock,
    ParagraphBlock,
    Provenance,
    RenderContract,
    ReportMetadata,
    RiskLevel,
    SectionIR,
    TableBlock,
    VerificationStatus,
    WarningBlock,
)

__all__ = [
    "ActionRecord",
    "ArtifactRecord",
    "Block",
    "CitationLocator",
    "CitationNoteBlock",
    "CitationRecord",
    "CitationRegistry",
    "ClaimBlock",
    "ClauseGroupBlock",
    "ClauseIdentity",
    "ClauseNode",
    "CollectionAudit",
    "CompileResult",
    "Diagnostic",
    "DiagnosticLocation",
    "DocumentCompiler",
    "DocumentIR",
    "DocxRenderer",
    "DocxRenderError",
    "DocxStats",
    "FindingBasis",
    "FindingDetailBlock",
    "FindingRecord",
    "FindingReferenceBlock",
    "FindingSummaryBlock",
    "FontRecord",
    "FontSpec",
    "GateResult",
    "Identity",
    "Integrity",
    "KeyValueBlock",
    "KeyValueItem",
    "Lifecycle",
    "ListBlock",
    "ListItem",
    "MarkdownRenderer",
    "NumberingStyle",
    "PageBreakBlock",
    "ParagraphBlock",
    "PassResult",
    "PdfRenderer",
    "PdfRenderError",
    "PdfStats",
    "Provenance",
    "RenderContract",
    "RenderError",
    "RenderManifest",
    "RenderingMode",
    "ReportMetadata",
    "RiskLevel",
    "SectionIR",
    "TableBlock",
    "VerificationStatus",
    "WarningBlock",
    "audit_ir_vs_legacy",
    "build_render_manifest",
    "extract_citation_refs",
    "legacy_item_to_record",
    "legacy_registry_to_reporting",
    "migrate_v3_document",
    "render_docx",
    "render_docx_to_file",
    "render_ir_artifacts",
    "render_markdown",
    "render_pdf",
    "render_pdf_to_file",
    "verify_render_manifest",
    "write_audit_json",
]
