from enum import Enum


class AssessmentTaskState(str, Enum):
    CREATED = "CREATED"
    PARSING = "PARSING"
    RETRIEVING = "RETRIEVING"
    GENERATING = "GENERATING"
    VALIDATING = "VALIDATING"
    RENDERING = "RENDERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
